var searchData=
[
  ['rc1_202026_2005_2031_0',['[1.0.1-rc1] - 2026-05-31',['../md_CHANGELOG.html#autotoc_md1',1,'']]],
  ['reconfiguration_1',['Reconfiguration',['../index.html#autotoc_md22',1,'']]],
  ['redis_2',['Redis',['../../redisx/doc/html/structRedis.html',1,'']]],
  ['redisclient_3',['RedisClient',['../../redisx/doc/html/structRedisClient.html',1,'']]],
  ['rediscluster_4',['RedisCluster',['../../redisx/doc/html/structRedisCluster.html',1,'']]],
  ['redisentry_5',['RedisEntry',['../../redisx/doc/html/structRedisEntry.html',1,'']]],
  ['redismap_6',['RedisMap',['../../redisx/doc/html/structRedisMap.html',1,'']]],
  ['redisserver_7',['RedisServer',['../../redisx/doc/html/structRedisServer.html',1,'']]],
  ['redisx_2dclient_2ec_8',['redisx-client.c',['../../redisx/doc/html/redisx-client_8c.html',1,'']]],
  ['redisx_2dcluster_2ec_9',['redisx-cluster.c',['../../redisx/doc/html/redisx-cluster_8c.html',1,'']]],
  ['redisx_2dhooks_2ec_10',['redisx-hooks.c',['../../redisx/doc/html/redisx-hooks_8c.html',1,'']]],
  ['redisx_2dnet_2ec_11',['redisx-net.c',['../../redisx/doc/html/redisx-net_8c.html',1,'']]],
  ['redisx_2dscript_2ec_12',['redisx-script.c',['../../redisx/doc/html/redisx-script_8c.html',1,'']]],
  ['redisx_2dsentinel_2ec_13',['redisx-sentinel.c',['../../redisx/doc/html/redisx-sentinel_8c.html',1,'']]],
  ['redisx_2dsub_2ec_14',['redisx-sub.c',['../../redisx/doc/html/redisx-sub_8c.html',1,'']]],
  ['redisx_2dtab_2ec_15',['redisx-tab.c',['../../redisx/doc/html/redisx-tab_8c.html',1,'']]],
  ['redisx_2dtls_2ec_16',['redisx-tls.c',['../../redisx/doc/html/redisx-tls_8c.html',1,'']]],
  ['redisx_2ec_17',['redisx.c',['../../redisx/doc/html/redisx_8c.html',1,'']]],
  ['redisx_2eh_18',['redisx.h',['../../redisx/doc/html/redisx_8h.html',1,'']]],
  ['refindex_19',['refIndex',['../structXCoordinateAxis.html#ad191af99a874bc633c0834d247427ea8',1,'XCoordinateAxis']]],
  ['refvalue_20',['refValue',['../structXCoordinateAxis.html#ad56f22fc3fbf9639a29ed9f174c67ec2',1,'XCoordinateAxis']]],
  ['related_20links_21',['Related links',['../index.html#autotoc_md10',1,'']]],
  ['release_20schedule_22',['Release schedule',['../index.html#autotoc_md67',1,'']]],
  ['releaseid_23',['RELEASEID',['../smax-private_8h.html#acb5965a4e56d8d90d76002bef3207ef9',1,'smax-private.h']]],
  ['remote_20control_20calls_20and_20return_20values_24',['Complex remote control calls and return values',['../index.html#autotoc_md50',1,'']]],
  ['remote_20program_20control_20via_20sma_20x_25',['Remote program control via SMA-X',['../index.html#autotoc_md47',1,'']]],
  ['resp_26',['RESP',['../../redisx/doc/html/structRESP.html',1,'']]],
  ['resp_2ec_27',['resp.c',['../../redisx/doc/html/resp_8c.html',1,'']]],
  ['return_20values_28',['Complex remote control calls and return values',['../index.html#autotoc_md50',1,'']]]
];
