name: CMake
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "include/**"
      - "test/**"
      - "**/CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/cmake.yml"

  pull_request:
    paths:
      - "src/**"
      - "include/**"
      - "test/**"
      - "**/CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/cmake.yml"

jobs:
  build:
    name: Full build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenSSL / OpenMP
        run: |
          sudo apt-get update -q -y
          sudo apt-get install doxygen libomp-dev libssl-dev libpopt-dev libreadline-dev libbsd-dev

      - name: Check out smax-clib
        uses: actions/checkout@v7

      - name: Check out xchange
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/xchange
          path: xchange

      - name: Check out RedisX
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/redisx
          path: redisx

      - name: Build xchange dependency
        run: |
          cd xchange
          cmake -B build -DBUILD_SHARED_LIBS=ON
          cmake --build build

      - name: Build RedisX dependency
        run: |
          cd redisx
          cmake -B build -Dxchange_DIR="../xchange/build" -DBUILD_SHARED_LIBS=ON -DENABLE_TLS=ON
          cmake --build build

      - name: Configure CMake
        run: cmake -B build -Dxchange_DIR="xchange/build" -Dredisx_DIR="redisx/build" -DBUILD_SHARED_LIBS=ON -DBUILD_CLI=ON -DBUILD_DOC=ON -DENABLE_TLS=ON

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build --prefix install

      - name: Check Installation
        run: |
          echo Installation contents:
          ls -la install/

  build-os:
    name: OS builds (defaults)
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out smax-clib
        uses: actions/checkout@v7

      - name: Check out xchange
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/xchange
          path: xchange

      - name: Check out RedisX
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/redisx
          path: redisx

      - name: Build xchange dependency
        run: |
          cd xchange
          cmake -B build
          cmake --build build --config Release

      - name: Build RedisX dependency
        run: |
          cd redisx
          cmake -B build -Dxchange_DIR="../xchange/build"
          cmake --build build --config Release

      - name: Configure CMake
        run: cmake -B build -Dxchange_DIR="xchange/build" -Dredisx_DIR="redisx/build"

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --prefix install

      - name: Check Installation (Unix)
        if: runner.os != 'Windows'
        run: |
          echo Installation contents:
          ls -la install/

      - name: Check Installation (Windows)
        if: runner.os == 'Windows'
        run: |
          echo Installation contents:
          dir install

  build-freebsd:
    name: Build on FreeBSD (defaults)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out smax-clib
        uses: actions/checkout@v7

      - name: Check out xchange
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/xchange
          path: xchange

      - name: Check out RedisX
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/redisx
          path: redisx

      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.0"
          usesh: true
          prepare: |
            pkg install -y cmake
          run: |
            echo Building on FreeBSD $(uname -m)
            cd xchange
            cmake -B build
            cmake --build build
            cd ../redisx
            cmake -B build -Dxchange_DIR="../xchange/build"
            cmake --build build
            cd ..
            cmake -B build -Dxchange_DIR="xchange/build" -Dredisx_DIR="redisx/build"
            cmake --build build
            cmake --install build --prefix install
            ls -la install/

  test-cmake:
    name: Test (Ubuntu)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install libpopt-dev libreadline-dev libbsd-dev libssl-dev
    
      - name: Check out smax-clib
        uses: actions/checkout@v7

      - name: Check out xchange
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/xchange
          path: xchange

      - name: Check out RedisX
        uses: actions/checkout@v7
        with:
          repository: Sigmyne/redisx
          path: redisx

      - name: Check out smax-server
        uses: actions/checkout@v7
        with:
          repository: Smithsonian/smax-server
          path: smax-server

      - name: Build xchange dependency
        run: |
          cd xchange
          cmake -B build -DBUILD_SHARED_LIBS=ON
          cmake --build build

      - name: Build RedisX dependency
        run: |
          cd redisx
          cmake -B build -Dxchange_DIR="../xchange/build" -DBUILD_SHARED_LIBS=ON
          cmake --build build --config Release

      - name: Build
        run: |
          cmake -B build -Dxchange_DIR="xchange/build" -Dredisx_DIR="redisx/build" -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON
          cmake --build build

      - name: install Redis
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y redis
          sudo sed -i "s:^protected mode[[:blank:]]*yes:protected mode no:g" /etc/redis/redis.conf

      - name: Start Redis server
        run: |
          sudo service redis-server start

      - name: Install SMA-X scripts
        run: |
          cd smax-server
          sudo ./install.sh auto

      - name: Enable smax host lookup
        run: |
          sudo echo "127.0.0.1 smax" | sudo tee -a /etc/hosts

      - name: Test
        run: ctest --test-dir build --output-on-failure
